services:
  casper:
    image: "phasecorex/red-discordbot"
    restart: "always"
    volumes:
      - "/var/lib/casper:/data"
    environment:
      - "TOKEN=$CASPER_DISCORD_TOKEN"
      - "PREFIX=!"

  boogiebot:
    image: "ghcr.io/nicksquiggles/boogiebot:main"
    restart: "always"
    volumes:
      - type: bind
        source: /var/lib/boogiebot/boogiebot.db
        target: /app/boogiebot.db
    environment:
      - "TOKEN=$BOOGIEBOT_DISCORD_TOKEN"
