services:
  casper:
    image: "phasecorex/red-discordbot"
    restart: "always"
    volumes:
      - "/var/lib/casper:/data"
    environment:
      - "TOKEN=$CASPER_DISCORD_TOKEN"
      - "PREFIX=!"

  boogiebot:
    image: "ghcr.io/nicksquiggles/boogiebot:main"
    restart: "always"
    volumes:
      - "/var/lib/boogiebot:/data"
    environment:
      - "TOKEN=$BOOGIEBOT_DISCORD_TOKEN"
      - "BOOGIEBOT_DB_PATH=/data/boogiebot.db"
