---
- hosts: all
  become: true
  tasks:
    # base machine setup
    - name: update apt cache
      apt:
        update_cache: true
    - name: install apt https prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
    - name: import docker repository gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: add docker apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: install docker
      apt:
        name: docker-ce
    # casper7
    - name: create /var/lib/casper7
      file:
        path: /var/lib/casper7
        state: directory
    - name: emplace casper7 database
      copy:
        src: casper.db
        dest: /var/lib/casper7/casper.db
        force: false
    - name: casper7
      docker_container:
        name: casper7
        image: ghcr.io/backwardspy/casper7:main
        pull: true
        recreate: true
        restart_policy: always
        env:
          DISCORD_TOKEN: "{{ lookup('ansible.builtin.env', 'DISCORD_TOKEN') | string }}"
          DATABASE_PATH: /var/lib/casper7/casper.db
          MEATBALL_ASSIGNMENT_SCHEDULE: "0 8-20 * * * *"
        volumes:
          - /var/lib/casper7/:/var/lib/casper7/
